### ISSUE TITLE
Growth factors and hormones in Beta-cell proliferation

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pathway-curation-tasks#17]
![image](https://user-images.githubusercontent.com/1442197/115793759-8b69af80-a381-11eb-8101-78b814a410c8.png)
Binding of growth factors and hormones to their respective receptors or ligands serves a pivotal role in β-cell proliferation (Fig 2)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6143874/

**Comment by danidi** [comment]
This figure is implemented as pathway here: https://classic.wikipathways.org/index.php/Pathway:WP5385
