### ISSUE TITLE
JAK-STAT signaling in the regulation of Beta-cells

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pathway-curation-tasks#18]
![image](https://user-images.githubusercontent.com/1442197/115793808-a3413380-a381-11eb-858f-16cee24ccc5a.png)

JAK-STAT signaling in tandem with multiple cytokines and hormones participates in the regulation of β-cells. (Fig 3)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6143874/

**Comment by IsabelWassink** [comment]
Hi, I made a pathway model of this figure: [WP5358](https://classic.wikipathways.org/index.php/Pathway:WP5358l). I was wondering how to proceed from here. Can I close this issue? Furthermore, the figure is mentioned on PFOCR page on WikiPathways: https://pfocr.wikipathways.org/figures/PMC6143874__etm-16-04-3275-g02.html. Is there anything I should do with that to mention the figure has been made into a pathway model? Thanks in advance!

**Comment by khanspers** [comment]
Hi @IsabelWassink, nice work! Yes, go ahead and close this issue. 

For the pathway figure on the [PFOCR site](https://pfocr.wikipathways.org/figures/PMC6143874__etm-16-04-3275-g02.html), a mapping to the corresponding WPID can be added by editing a [mapping table](https://github.com/wikipathways/pfocr-database/blob/main/_data/wpid_map.tsv), however only owners of that repo can edit it. I just made the update to add the mapping between PMC6143874__etm-16-04-3275-g02 and WP5358. The site is rebuilding now, the link to the WikiPathways model will appear as a badge under the figure.
