### ISSUE TITLE
Warburg effect modulated by deubiquitinating enzymes and their substrates, WP5216, Homo sapiens

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pathway-curation-tasks#22]
### Curation tasks:

- Add node annotations (xrefs)
- Connect interactions
- Description indicates some of the arrows should be blue(for transcriptional stimulatory modification). Figure out if this information is available in the reference paper/figure and add it.

- Instructions for editing pathways are available here: https://academy.wikipathways.org/stages/walk-install-pv/.*

**Comment by danidi** [comment]
This is currently being worked on as a student project.

**Comment by danidi** [comment]
All open curation tasks have been completed. Is anything else needed for approval of the pathway?

**Comment by khanspers** [comment]
I added the Approved tag. Thanks for completing the pathway!
