### ISSUE TITLE
[Improve Pathway]: 

### ISSUE THREAD

**Issue by cereno98** [wikipathways/pathway-curation-tasks#24]
### Pathway URL

https://github.com/wikipathways/pathway-curation-tasks/issues/17 

### Suggested imoprovements

The pathway is missing database identifiers and inetractions!

**Comment by khanspers** [comment]
The issue you are linking to describes a figure from a paper that could be translated to a pathway model, so by definition it is lacking database identifiers and proper interactions. It does not describe a completed pathway. Closing this.
