### ISSUE TITLE
Regulation of the TGFB/Smad signaling pathway in glaucoma

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pathway-curation-tasks#8]
![image](https://user-images.githubusercontent.com/1442197/115471538-fe8ded00-a1ec-11eb-90fe-f7b4609e7c3c.png)
Regulation of the TGF-β/Smad signaling pathway in glaucoma (Fig 4)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5819904/

**Comment by danidi** [comment]
This figure is converted to a pathway here: https://classic.wikipathways.org/index.php/Pathway:WP5382

**Comment by khanspers** [comment]
Fantastic!
